### ISSUE TITLE
Not working in MacOS Sonoma

### ISSUE THREAD

**Issue by CthulhuDen** [mweirauch/dropignore#24]
**Describe the bug**
Attributes set by this app seem to have no effect on dropbox sync status of files and folders.

**To Reproduce**

1. Be running in MacOS Sonoma

2. Take the following config and put it in `~/Library/Application Support/dropignore/dropignore.yml`:
```
matcher:
  ignore-specs:
    - pattern: "**/ignore_this"
```

3. Somewhere in Dropbox location create folder (which is made available offline) with two subfolders: `ignore_this` and `keep_this`
<img width="471" alt="image" src="https://github.com/mweirauch/dropignore/assets/3912367/8070c598-9d02-4060-8586-682807259a62">

4. Run `dropignore scan <path_to_filder>`

**Expected behavior**
The subdirectory ignore_this is ignored by dropbox.

**Screenshots or log output**

Nothing changes on the Finder screenshot above.

```
[INFO ][scanner      ] SCAN    "/Users/denis/Library/CloudStorage/Dropbox/delme"
[INFO ][scanner      ] IGNORED "/Users/denis/Library/CloudStorage/Dropbox/delme/ignore_this"
[INFO ][scanner      ] Finished with 0 known and 1 new ignores.
```

**Environment:**
 - OS: macOS 14.1.2
 - `dropignore` Version: 0.1.2-alpha.0

**Additional context**

Examine the attributes on the directory in question:
```
denis@Denis-MBA delme % xattr -l ignore_this
com.dropbox.attrs:

�
 N�w
    ��
com.dropbox.internal:
user.com.dropbox.ignored: 1
```
It appears `user.` prefix is not needed in macOS.

Besides, official documentation at https://help.dropbox.com/sync/ignored-files (which is written poorly for ignoring files on Mac, better read unignore section and invert commands) also advises setting second attribute (com.apple.fileprovider.ignore#P) for modern MacOS versions.

Here is how it looks after running the following:
```
denis@Denis-MBA delme % xattr -w com.dropbox.ignore 1 ignore_this
denis@Denis-MBA delme % xattr -w 'com.apple.fileprovider.ignore#P' 1 ignore_this
```
<img width="476" alt="image" src="https://github.com/mweirauch/dropignore/assets/3912367/da826fd1-0aec-464f-bf2a-8b3f0b730661">

which seems to be the expected result

**Comment by CthulhuDen** [comment]
Here's how I fixed it for myself: https://github.com/CthulhuDen/dropignore/commit/7dfc28afad1d2acebaa9b6af3d9f092d099fe9b5. 

I will create Pull Request if you are interested

**Comment by mweirauch** [comment]
I haven't had the time to look closer, but it's very welcome to open up a Pull Request! (especially as I don't have such an environment around)
