### ISSUE TITLE
osX installation guide

### ISSUE THREAD

**Issue by ctrlok** [mweirauch/dropignore#28]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of how to install the project on macOS

# <start>

Hi there! It's a cool app and works great as well. I was surprised that xattr `com.apple.fileprovider.ignore#P` works for iCloud as well 

I managed to run dropignore under macOS, and I think it can be helpful for other macOS users. I don't know where is a best place to add it. I can create some file like "osx_install_guide.md" and link it to the main readme. Or you can place this instruction where you want. 

Thanks for the app again. 

# Guide for macOS 

1. Install rust via `brew` or `rustup` 
2. Install the latest version of dropignore via `cargo install --git https://github.com/mweirauch/dropignore` 
3. Create config in `~/Library/Application\ Support/dropignore/dropignore.yml` 
4. test if app works as expected with `dropignore watch  $HOME/Library/CloudStorage/Dropbox/` 
5. Create launchd plist to run it as a daemon in `$HOME/Library/LaunchAgents/com.user.dropignore.plist`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.dropignore</string>
    <key>ProgramArguments</key>
    <array>
        <string>sh</string>
        <string>-c</string>
        <string>$HOME/.cargo/bin/dropignore watch $HOME/Library/CloudStorage/Dropbox/</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>

``` 

7. launch script
```bash
launchctl load ~/Library/LaunchAgents/com.user.dropignore.plist
```

8. To remove it — run 
```bash
launchctl unload ~/Library/LaunchAgents/com.user.dropignore.plist
```

to debug startup script run:

```bash
log show --predicate 'eventMessage contains "com.user.dropignore"' --info --last 1h
```

**Comment by mweirauch** [comment]
Heya! Thanks for the detailed information! I have created #29 which updates the README accordingly. I took the chance to also document the systemd setup, as that one was open as well.

I tried to be a little more concise as the installation parts should already have been covered.

**Comment by ctrlok** [comment]
Thanks! That's looks great!

**Comment by devope** [comment]
It is a really great guide for macOS. May be there is a chance to link it in `README.md`.
