### ISSUE TITLE
Pass a config file

### ISSUE THREAD

**Issue by devope** [mweirauch/dropignore#30]
**Is your feature request related to a problem? Please describe.**
I can not figure it out is my config applied or not.

**Describe the solution you'd like**
Would be great to pass a flag with the path to config file

**Describe alternatives you've considered**
Couldn't figure it out, may be you can help to find a workaround for this situation?

**Comment by devope** [comment]
Actually I found out that in the `README.md` was mentioned a wrong file to config.
On macOS it is: `~/Library/Application\ Support/dropignore/dropignore.yml`.

I moved my settings there and everything work just fine.

**Comment by mweirauch** [comment]
Thanks for reporting @devope. I missed to update the documentation when updating one of the dependencies in which this was fixed to the correct/recommended location a long while ago.

PS: I still need to release a newer version with some other fix which has already been incorporated. Until then you'd need to run your local build. But I guess you are already doing so.
